// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NibulonUrkPosta.Persistance;

#nullable disable

namespace NibulonUrkPosta.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250309204944_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NibulonUrkPosta.Models.Aup.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CITY_KOD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CITY");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("KRAJ");

                    b.Property<short>("RegionId")
                        .HasColumnType("smallint")
                        .HasColumnName("OBL");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("RegionId");

                    b.ToTable("CITY", (string)null);
                });

            modelBuilder.Entity("NibulonUrkPosta.Models.Aup.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KRAJ");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("RAJ");

                    b.HasKey("Id");

                    b.ToTable("RAJ", (string)null);
                });

            modelBuilder.Entity("NibulonUrkPosta.Models.Aup.PostIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CITY");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NCITY");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("RAJ");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NRAJ");

                    b.Property<string>("PostIndexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("INDEX_A");

                    b.Property<short>("RegionId")
                        .HasColumnType("smallint")
                        .HasColumnName("OBL");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOBL");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("RegionId");

                    b.ToTable("AUP", (string)null);
                });

            modelBuilder.Entity("NibulonUrkPosta.Models.Aup.Region", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("OBL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOBL");

                    b.HasKey("Id");

                    b.ToTable("OBL", (string)null);
                });

            modelBuilder.Entity("NibulonUrkPosta.Models.Aup.City", b =>
                {
                    b.HasOne("NibulonUrkPosta.Models.Aup.District", "District")
                        .WithMany("Cities")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NibulonUrkPosta.Models.Aup.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NibulonUrkPosta.Models.Aup.PostIndex", b =>
                {
                    b.HasOne("NibulonUrkPosta.Models.Aup.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NibulonUrkPosta.Models.Aup.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NibulonUrkPosta.Models.Aup.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NibulonUrkPosta.Models.Aup.District", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("NibulonUrkPosta.Models.Aup.Region", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
